### ISSUE TITLE
Can you allow change chanel while video playng?

### ISSUE THREAD

**Issue by ehaab** [bbk79/xbmc-addons#23]
Could you allow us change channel while video playing?for example show video list over video just like live tv simple addon.Furthermore is there any way to add hd streams as well? Thanks for cool addon.

**Comment by bbk79** [comment]
Better late than never I guess, this one has been sitting here for more than 4 years now 😬My apologies as I don't actively monitor this repository.

I'm guessing you were referring to the GLWiz add-on which I ended up deprecating due to lack of time and other commitments.
