### ISSUE TITLE
Manotv Add-on on Kodi 17.6

### ISSUE THREAD

**Issue by sghazagh** [bbk79/xbmc-addons#25]
Hi,
Manoto TV add-on was working for me for long time. But there is no video and it even does not start.
Is there video VC-1 codec related issue or there is anything else.
Can you please advise if I have to but a codec or there is something else.

Many thanks,
Saeid/Australia

**Comment by sghazagh** [comment]
I already have purchased the codec but still has some issue. cannot start the stream most of the time, but could be able to run and see it once!!!
Any issue with plugin or manototv itself?

**Comment by bbk79** [comment]
My apologies as I don't actively monitor this repository, latest version should be working fine.
