### ISSUE TITLE
problem in retrieving the stream URL

### ISSUE THREAD

**Issue by Saina199** [bbk79/xbmc-addons#26]
Hi, 

I have been using this add-on for more than two years now.  Since August 25th, I have been encountering this error.

**Comment by bbk79** [comment]
Hi there, 

Apologies for the late response as I don't actively monitor this repository.

Latest Manoto update should fix the issue, I had to deprecate the GLWiz add-on after a breaking change on the GLWiz website as I no longer have enough time to maintain it.

Cheers,
Babak
